const Question = [
  "Voice Modulation",
  "Speed Of Delivery",
  "Presentation",
  "Communication Skill",
  "Interest/Motivation Generated By Teacher",
  "Knowledge Base Of The Teacher As You Received",
  "Assessibility Of The Teacher In And Out Of The Class",
  "How Simulating The Lectures Are",
  "Temperament For The Encouraging Question To The Class",
  "Regularity And Punctuality",
  "Overall Rating",
];

export default Question;
