const TeacherList = [
  {
    department: "Industrial Production",
    semester: "I",
    faculty: [
      "Mr. Sonu Ram",
      "Dr. Bhaskar Sharma",
      "Mr. Vicky Lad",
      "Dr. Aradhana Soni",
      "Mr. Rochak Pandey",
      "Mr. Mukesh Kumar Ray",
    ],
  },
  {
    faculty: [
      "Mr. C.P. Dhuri",
      "Dr. S.K. Singh",
      "Mr. Prakhar Modi",
      "Dr. Princy Matlani",
      "Ms. Preeti Singh",
      "Mr. Mukesh Kumar Ray",
    ],
    department: "Chemical",
    semester: "I",
  },
  {
    faculty: [
      "Dr. R.K. Pandey",
      "Mr. Jitendra Bhardwaj",
      "Mr. Amit Kumar Dewangan",
      "Dr. D.S. Singh",
      "Ms. Twinkle Kumar",
      "Mr. Anurag Singh",
      "Mr. Rajeev Shrivastava",
    ],
    department: "Information Technology",
    semester: "I",
  },

  {
    faculty: [
      "Dr. Bivash Dolai",
      "Dr. Santosh Verma",
      "Mrs. Anita Khanna",
      "Mr. Amit Kumar Dewangan",
      "Dr. Neetu Baghel",
      "Mr. Kailash Kumar Borkar",
      "Mr. Rajeev Shrivastava",
    ],
    department: "Electronics and Communication",
    semester: "I",
  },
  {
    faculty: [
      "Mr. Amit Kumar Dewangan",
      "Mr. Sumit Gupta",
      "Dr. Parijat Thakur",
      "Dr. Brijendra Paswan",
      "Mr. Dennis Thomas",
      "Mr. Somnath Singroul",
      "Mr. Annu Lal Mahato",
    ],
    department: "Computer Science",
    semester: "I",
  },
  {
    faculty: [
      "Dr. Chirjeev Yadav",
      "Dr. V.K. Rai",
      "Mrs. Shweta Singh",
      "Mr. Pushpendra Kumar Chandra",
      "Mr. Vinod Kumar",
      "Mr. Mukesh Kumar Ray",
    ],
    department: "Mechenical",
    semester: "I",
  },
  {
    faculty: [
      "Mr. Hapka Surendra",
      "Dr. Neeraj Kumari",
      "Mrs. Sonal Banchor",
      "Mr. Pushpendra Kumar Chandra",
      "Ms. Preeti Singh",
      "Mr. Mukesh Kumar Ray",
    ],
    department: "Civil",
    semester: "I",
  },
  {
    faculty: [
      "Mr. M.C. Rao",
      "Mr. Ashish Parashar",
      "Mr. Vikas Chandani",
      "Ms. Ayushi Nayak",
      "Mr. Rochak Pandey",
      "Ms. Tanuja Gupta",
    ],
    department: "Civil",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. Vaibhav Kant Singh",
      "Mr. Satish Kumar Negi",
      "Mrs. Nishi Yadav",
      "Ms. Nikita Kashyap",
      "Mr. Chandrashekhar",
    ],
    department: "Computer Science",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. Md. Asad",
      "Mr. Sonu Raj",
      "Ms. Jasinta Ekka",
      "Mrs. Shweta Singh",
      "Mr. Manish Bhaskar",
      "Mr. MS Anoop Sahu",
    ],
    department: "Mechenical",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. Amit Khaskalam",
      "Mr. Deepak Netam",
      "Mr. Abhishek Jain",
      "Mr. Agnivesh Pandey",
      "Mr. Amar Pandey",
    ],
    department: "Information Technology",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. C.P. Dewangan",
      "Mr. N.K. Sahu",
      "Mr. Leeladhar",
      "Ms. Arpita",
    ],
    department: "Industrial Production",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. Sankirtan Sardar",
      "Mr. Vishnu Prasad Yadav",
      "Mr. Gautam Prasad Dewangan",
      "Dr. Neetu Baghel",
      "Mr. Saurabh Mesharam",
    ],
    department: "Chemical",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. Sankarlan Sardar",
      "Ms. Niki Baghel",
      "Mr. B. Nath",
      "Mr. Chandan Tamrakar",
      "Dr. P.S. Shrivastava",
      "Ms. Pragati Patharia",
    ],
    department: "Electronics and Communication",
    semester: "IV",
  },
  {
    faculty: [
      "Mr. Amit Jain",
      "Dr. Anil Chandrakar",
      "Dr. Ghoshna Jyoti",
      "Mrs. A.N Joshi",
      "Prof. S.N Saha",
      "Mr. Saurabh Mesharam",
      "Dr. Sandeep Dharmadhikari",
    ],
    department: "Chemical",
    semester: "VI",
  },

  {
    faculty: [
      "Mr. Anand Prakash Rawal",
      "Mr. Suhel Ahmed",
      "Mrs. Akanksha Gupta",
      "Mr. Pankaj Chandra",
      "Dr. Amit Kumar Khaskalam",
    ],
    department: "Information Technology",
    semester: "VI",
  },
  {
    faculty: [
      "Mr. Vaibhav Kant Singh",
      "Mrs. Nishi Yadav",
      "Mr. Manjit Jaiswal",
      "Mr. Amit Baghel",
      "Dr. Devendra Kumar Singh",
      "Ms. Raksha Pandey",
    ],
    department: "Computer Science",
    semester: "VI",
  },
  {
    faculty: [
      "Mr. Vinod Kumar",
      "Dr. Kundan Meshram",
      "Mr. Nikhil Kumar",
      "Ms. Ayushi Nayak",
      "Mr. Akash Parashar",
      "Dr. Rajender Kumar",
      "Dr. V.V.S Surya Kumar",
    ],
    department: "Civil",
    semester: "VI",
  },
  {
    faculty: [
      "Mr. Bhushan Singh Gautam",
      "Mr. Manish Bhaskar",
      "Dr. Anoop Kumar Sahu",
      "Mr. Pradeep Patanwar",
      "Mrs. Shweta Singh",
      "Mr. Prashant Jangde",
    ],
    department: "Mechenical",
    semester: "VI",
  },
  {
    faculty: [
      "Dr. Manish Srivastava",
      "Mrs. Princy Matlani",
      "Mr. Nishant Behar",
    ],
    department: "Computer Science",
    semester: "VIII",
  },
  {
    faculty: [
      "Mr. Deepak Netam",
      "Mr. Rajesh Mahule",
      "Dr. Rohit Raja",
      "Mr. Santosh Soni",
      "Mr. Pankaj Chandra",
    ],
    department: "Information Technology",
    semester: "VIII",
  },
  {
    faculty: [
      "Mr. Prashant Jangde",
      "Mr. Prateek Gupta",
      "Dr. Pankaj Kumar Gupta",
      "Mr. Biplab Das",
    ],
    department: "Mechenical",
    semester: "VIII",
  },
  {
    faculty: [
      "Dr. Raghwendra Singh Thakur",
      "Mr. Gautam Prasad Dewangan",
      "Mr. Amit Jain",
      "Dr. Sandeep Dharmadhikari",
      "Mr. Neeraj Chandraker",
    ],
    department: "Chemical",
    semester: "VIII",
  },
  {
    faculty: [
      "Dr. V.V.S Surya Kumar",
      "Ms. Ayushi Nayak",
      "Ms. Preeti Singh",
      "Dr. Kundan Meshram",
      "Dr. M.C. Rao",
      "Mr. Nikhil Kumar",
    ],
    department: "Civil",
    semester: "VIII",
  },
];

export default TeacherList;
